# Generated by Django 3.0.7 on 2020-06-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='introduce',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qq',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, null=True)),
                ('sex', models.CharField(max_length=10, null=True)),
                ('age', models.SmallIntegerField(null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('image', models.CharField(max_length=254, null=True)),
                ('introduce', models.TextField(null=True)),
                ('info', models.TextField(null=True)),
                ('email', models.CharField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('qq', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.User')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
